(4-3)中級 パンくずリスト修正
Masayuki1009/ex-emp-management-bugfix pull request #10
Opened 2022-11-21 02:52 UTC by Masayuki1009

従業員詳細ページのパンくずリストから従業員一覧ページに戻れるよう修正しました。

2022-11-21 04:59 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-21 04:59 UTC, igamasayuki commented on src/main/resources/templates/employee/detail.html
> +        <li>従業員詳細</li>
class="active"

は消さないようにしてください。

2022-11-21 05:07 UTC, Masayuki1009 commented on src/main/resources/templates/employee/detail.html
> +        <li>従業員詳細</li>
class="active"を追加しました。

2022-11-22 06:41 UTC, igamasayuki approved these changes
レビューの指示が曖昧だったかもしれないので、こちらで正しく修正してみました。
ご確認いただければと思います。

レビューは完了状態にします。

2022-11-22 06:41 UTC, merged