(4-1)初級 日付フォーマット
Masayuki1009/ex-emp-management-bugfix pull request #7
Opened 2022-11-18 07:01 UTC by Masayuki1009

従業員リストの日付表記を〇〇〇〇年◯◯月〇〇日というフォーマットに変更しました。
ご確認をお願いいたします。

2022-11-18 08:54 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-18 08:54 UTC, igamasayuki commented on src/main/resources/templates/employee/list.html
> +                  <span th:text="${#dates.format(employee.hireDate, 'yyyy年MM月dd日')}">2016/12/1</span>
詳細画面にも同様の処理を行なってください。

2022-11-21 01:28 UTC, Masayuki1009 commented on src/main/resources/templates/employee/list.html
> +                  <span th:text="${#dates.format(employee.hireDate, 'yyyy年MM月dd日')}">2016/12/1</span>
詳細画面のhireDateにも同様のフォーマット処理を行いましたので、ご確認をお願いいたします。

2022-11-21 04:55 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2022-11-21 04:55 UTC, merged